# Generated by Django 3.2.4 on 2023-03-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.BigIntegerField()),
                ('booking_id', models.CharField(max_length=100)),
                ('location_id', models.CharField(max_length=100)),
                ('drone_shot_id', models.CharField(max_length=100)),
                ('created_time', models.CharField(max_length=100)),
            ],
        ),
    ]
